Plugin Size Reduction
KatharaFramework/NetworkPlugin pull request #6
Opened 2021-11-29 16:40 UTC by whatever4711

Simply changing the base image for the plugin from Debian to Alpine reduces the size from 60MB to 10MB for the plugin. This is beneficial for all small devices like the RPi. Therefore, the `Dockerfile` is changed and the goal `gobuild_docker_%` is updated to use `golang:alpine3.14`.

2021-12-01 18:01 UTC, Skazza94 commented
Hi @whatever4711,
thanks for the PR. Seems good to have a smaller Network Plugin image. We used Debian while developing it for faster debugging, but now it is ok to switch to Alpine. @lorenzo93 will take care of it.

2021-12-03 17:27 UTC, lorenzo93 requested changes
Hi @whatever4711 ,

Your idea is really smart and I like it :)

The network plugin automatically switches at runtime between `iptables` and `nftables`. This is needed due to the compatibility with different linux distros (different distros uses different versions and they are not cross-compatible).

I've added to the review the changes to be compatible with all the distros.

2021-12-03 17:27 UTC, lorenzo93 commented on img-src/Dockerfile
>      iptables
To make the plugin work, we need both iptables and nftables.
Moreover, due to the switch [here](https://github.com/KatharaFramework/NetworkPlugin/blob/master/go-src/src/common_utils.go#L47) and [here](https://github.com/KatharaFramework/NetworkPlugin/blob/c0bc61a5ad16de974c963e4f33e559e1dc51232a/go-src/src/common_utils.go#L51) we need also `dpkg` installed into the container (`update-alternatives` is a part of the `dpkg` package)
So this should install all this requirements and be something like this
`apk add -U iptables dpkg nftables`

2021-12-03 17:27 UTC, lorenzo93 commented on img-src/Dockerfile
> -RUN apt clean
You should add the equivalent for `apk` to have the image smaller.
According to [this thread](https://stackoverflow.com/questions/49118579/alpine-dockerfile-advantages-of-no-cache-vs-rm-var-cache-apk) the best way is to run `apk add` with the `--no-cache` parameter

2021-12-03 17:27 UTC, lorenzo93 commented on img-src/Dockerfile
> -
To make `update-alternatives` working, the alternatives must be registered.
This are simple examples that I already tested in an alpine container:
- `update-alternatives --install /sbin/iptables iptables /sbin/iptables-legacy 1`
- `update-alternatives --install /sbin/iptables iptables /sbin/iptables-nft 2`

2021-12-03 17:29 UTC, lorenzo93 commented on img-src/Dockerfile
> -
I don't know how to comment on a file without selecting a line, so I commented a random line about this. ;)

2021-12-03 17:43 UTC, whatever4711 commented
@lorenzo93: I updated your suggestions on the latest commit. Thanks for your efforts.

2021-12-03 17:56 UTC, lorenzo93 approved these changes

2021-12-03 17:58 UTC, lorenzo93 commented
For me it is everything ok.

I'll merge and close this PR when I'll publish the new plugin with alpine (during next week).

Many thanks for the PR and changes.

2021-12-06 11:44 UTC, merged

2021-12-09 14:53 UTC, Skazza94 commented
Hi @whatever4711,
I pushed the new plugin containers which use Alpine.

Thanks for the PR.

Mariano.